### PR TITLE
New datetime parameter into write_iter.

### PR DESCRIPTION
**Pull request by okmetti**

### CODE REVIEW

**Comment by okmetti** [comment]
We would like to add date and time when using wrie_iter. The appropriate test included.

**Comment by arjan-s** [comment]
Thank you for your PR. I will review and test it shortly and post an update here.

**Comment by okmetti** [comment]
Thanks @arjan-s .

**Comment by arjan-s** [comment]
No problem. A new release with your change is on PyPI now.

**Pull request merged**
