### PR TITLE
Add partial flushing of ZipStreams

### PR DESCRIPTION
**Pull request by kageurufu**
I use this to flush partial zips as files are streamed into
 them from requests, and then at the end add manifest and
 error files to the end of the archive

I've also added a related test and example of use

### CODE REVIEW

**Comment by kageurufu** [comment]
This is currently possible through manually calling `__write`, but thats messy and with Python3's private method name mangling it is difficult to do cleanly (you call `self._ZipFile__write()`)

**Comment by arjan-s** [comment]
Hi, thank you for your contribution! I'll look at this shortly.

**Comment by arjan-s** [comment]
Thank you for your contribution. It has been included in a new release that is now also available on PyPI.

**Comment by kageurufu** [comment]
Awesome, thank you!

Glad to help

**Pull request merged**
